services:
  - type: web
    name: mina-agent
    env: node
    region: singapore
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 3000
